# 1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
    
   Region B: [18, 20, 16, 22, 25]

   Calculate the mean sales for each region.


In [8]:
import pandas as pd
import numpy as np
import statistics as stat
import scipy.stats as stats
import math
A=[10,15,12,8,14]
B=[18,20,16,22,25]
df1=pd.DataFrame(A)
print("A",df1)
print("Mean of region A:",stat.mean(A))


A     0
0  10
1  15
2  12
3   8
4  14
Mean of region A: 11.8


In [7]:
df2=pd.DataFrame(B)
print("B",df2)
print("Mean of Region B:",stat.mean(B))

B     0
0  18
1  20
2  16
3  22
4  25
Mean of Region B: 20.2



# 2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
    
   Calculate the mode of the survey responses.


In [10]:
data=[4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
print("scale",pd.DataFrame(data))
print("mode of the survey response:",stat.mode(data))

scale    0
0  4
1  5
2  2
3  3
4  5
5  4
6  3
7  2
8  4
9  5
mode of the survey response: 4



# 3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
    
   Department B: [4500, 5500, 5800, 6000, 5200]

   Calculate the median salary for each department.


In [46]:
A: [5000, 6000, 5500, 7000]
B: [4500, 5500, 5800, 6000, 5200]
A,B
print("median of department A AND B are :",stat.median(A),",",stat.median(B))

median of department A AND B are : 90 , 87



# 4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
    
   Calculate the range of the stock prices.


In [40]:
data=[25.5, 24.8, 26.1, 25.3, 24.9]
data

[25.5, 24.8, 26.1, 25.3, 24.9]

In [39]:
min_val = min(data)
max_val = max (data)
range_data = (min_val, max_val)
print(range_data)

(24.8, 26.1)



# 5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
    
   Group B: [82, 88, 90, 86, 87]

   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


 A t-test is a type of inferential statistic used to determine if there is a significant difference between the means of two groups

In [30]:
A=np.array([85, 90, 92, 88, 91])
B=np.array( [82, 88, 90, 86, 87])
A,B
result=stats.ttest_ind(a=A, b=B, equal_var=True)

In [31]:
A,B,result


(array([85, 90, 92, 88, 91]),
 array([82, 88, 90, 86, 87]),
 Ttest_indResult(statistic=1.4312528946642733, pvalue=0.19023970239078333))

# 6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    
   Sales (in thousands): [25, 30, 28, 20, 26]

   Calculate the correlation coefficient between advertising expenditure and sales.


In [16]:
X=np.array([10, 15, 12, 8, 14])
y=np.array([25, 30, 28, 20, 26])

In [17]:
X,y

(array([10, 15, 12,  8, 14]), array([25, 30, 28, 20, 26]))

In [21]:
def Pearson_correlation(X,Y):
    if len(X)==len(Y):
        Sum_xy = sum((X-X.mean())*(Y-Y.mean()))
        Sum_x_squared = sum((X-X.mean())**2)
        Sum_y_squared = sum((Y-Y.mean())**2)      
        corr = Sum_xy / np.sqrt(Sum_x_squared * Sum_y_squared)
    return corr
             
print("Relation between Expenditure and Sales:",Pearson_correlation(X,y))   
print(Pearson_correlation(X,X))

Relation between Expenditure and Sales: 0.8757511375750133
1.0



# 7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
    
   Calculate the standard deviation of the heights.


In [47]:
data=[160, 170, 165, 155, 175, 180, 170]
print("standard deviation:",stat.stdev(data))

standard deviation: 8.591246929842246



# 8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
    
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]

   Perform a linear regression analysis to predict job satisfaction based on employee tenure.



In [48]:
X=[2, 3, 5, 4, 6, 2, 4]
y=[7, 8, 6, 9, 5, 7, 6]
X,y


([2, 3, 5, 4, 6, 2, 4], [7, 8, 6, 9, 5, 7, 6])

In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression
X=pd.DataFrame([2, 3, 5, 4, 6, 2, 4])
y=pd.DataFrame([7, 8, 6, 9, 5, 7, 6])

X,y

(   0
 0  2
 1  3
 2  5
 3  4
 4  6
 5  2
 6  4,
    0
 0  7
 1  8
 2  6
 3  9
 4  5
 5  7
 6  6)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.20,random_state=42)

In [62]:
X_train,y_train,X_test,y_test


(   0
 5  2
 2  5
 4  6
 3  4
 6  4,
    0
 5  7
 2  6
 4  5
 3  9
 6  6,
    0
 0  2
 1  3,
    0
 0  7
 1  8)

In [63]:
X_train.shape,X_test.shape

((5, 1), (2, 1))

In [64]:
y_train,y_test

(   0
 5  7
 2  6
 4  5
 3  9
 6  6,
    0
 0  7
 1  8)

In [11]:
from sklearn.preprocessing import StandardScaler

In [66]:
scaler=StandardScaler()

In [67]:
x_train=scaler.fit_transform(X_train)

In [68]:
x_test=scaler.transform(X_test)

In [69]:
x_train,x_test

(array([[-1.6583124 ],
        [ 0.60302269],
        [ 1.35680105],
        [-0.15075567],
        [-0.15075567]]),
 array([[-1.6583124 ],
        [-0.90453403]]))

In [18]:
from sklearn.linear_model import LinearRegression

In [71]:
regressor=LinearRegression()

In [72]:
regressor.fit(x_train,y_train)

LinearRegression()

In [73]:
regressor.intercept_

array([6.6])

In [74]:
regressor.coef_

array([[-0.69347609]])

In [75]:
# prediction for test data
y_pred_test=regressor.predict(x_test)

In [76]:
y_pred_test

array([[7.75      ],
       [7.22727273]])

In [77]:
y_test

0
0  7
1  8

# 9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   Medication A: [10, 12, 14, 11, 13]
    
   Medication B: [15, 17, 16, 14, 18]

   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.



# 10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    
    Calculate the 75th percentile of the feedback ratings.


In [83]:
data=[8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
pd.DataFrame(data)

0
0   8
1   9
2   7
3   6
4   8
5  10
6   9
7   8
8   7
9   8

# 11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [93]:
data=[10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
mean=stat.mean(data)
print("mean weights",mean)

mean weights 10.15


In [94]:
if mean>=10:
    
    print("We accept the null hypothesis ")
    
    
    
else:
        print("We reject the null hypothesis")

We accept the null hypothesis 



# 12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    
    Design B: [80, 85, 90, 95, 100]
    
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [14]:
expected_data=[70, 100, 100, 90, 90]
obserbed_data= [80, 85, 90, 95, 100]

In [15]:
expected_data,obserbed_data

([70, 100, 100, 90, 90], [80, 85, 90, 95, 100])

In [16]:
sum(expected_data)

450

In [17]:
sum(obserbed_data)

450

In [18]:
import scipy.stats as stat
import numpy as np
chisquare_test_ststistc,p_value=stat.chisquare(obserbed_data,expected_data)

In [19]:
chisquare_test_ststistc,p_value

(6.067460317460318, 0.19416662182139688)

In [20]:
#find critical value
significance_value=0.05
dof=len(expected_data)-1
print(dof)
critical_value=stat.chi2.ppf(1-significance_value,dof)

4


In [21]:
critical_value

9.487729036781154

In [22]:
if chisquare_test_ststistc>critical_value:
    print("we reject the Null Hypothesis")
else:
    print("We accept the Null Hypothesis")
    

We accept the Null Hypothesis



# 13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    
    Calculate the 95% confidence interval for the population mean satisfaction score.



In [25]:
data=[7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
data
stat.t.interval(alpha=0.90, df=len(data)-1,
loc=np.mean(data),
scale=stat.sem(data))

/tmp/ipykernel_10484/2838519984.py:3: DeprecationWarning: Use of keyword argument `alpha` for method `interval` is deprecated. Use first positional argument or keyword argument `confidence` instead.
  stat.t.interval(alpha=0.90, df=len(data)-1,


(7.205994644530591, 8.59400535546941)

# 14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    
    Perform a simple linear regression to predict performance based on temperature.


In [6]:
import pandas as pd
import numpy as np
X=pd.DataFrame([20, 22, 23, 19, 21])
y=pd.DataFrame([8, 7, 9, 6, 8])

In [5]:
print(X)
print(y)

    0
0  20
1  22
2  23
3  19
4  21
   0
0  8
1  7
2  9
3  6
4  8


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.20,random_state=42)

In [14]:
X_train,X_test,y_train,y_test

(   0
 5  2
 2  5
 4  6
 3  4
 6  4,
    0
 0  2
 1  3,
    0
 5  7
 2  6
 4  5
 3  9
 6  6,
    0
 0  7
 1  8)

In [15]:
X_test.shape,X_train.shape

((2, 1), (5, 1))

In [17]:
y_train.shape,y_test.shape

((5, 1), (2, 1))

In [19]:
regressor=LinearRegression()

In [20]:
regressor.fit(X_train,y_train)

LinearRegression()

In [22]:
# prediction for test data
y_pred_test=regressor.predict(X_test)

In [23]:
y_pred_test

array([[7.75      ],
       [7.22727273]])

In [24]:
y_test

0
0  7
1  8

In [25]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [26]:
mse=mean_squared_error(y_test,y_pred_test)
mae=mean_absolute_error(y_test,y_pred_test)
rmae=np.sqrt(mse)

In [27]:
print(mse)
print(mae)
print(rmae)

0.579803719008265
0.7613636363636367
0.761448434897771


In [28]:
from sklearn.metrics import r2_score

In [29]:
score=r2_score(y_test,y_pred_test)
score

-1.31921487603306

# 16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    
    Calculate the interquartile range (IQR) of the ages.


In [33]:
import numpy 
x=[25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
q1_x = numpy.percentile(x, 25, interpolation='midpoint')

q3_x = numpy.percentile(x, 75, interpolation='midpoint')
print("IQR",q3_x - q1_x)

IQR 20.0


/tmp/ipykernel_104/2169921470.py:3: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  q1_x = numpy.percentile(x, 25, interpolation='midpoint')
/tmp/ipykernel_104/2169921470.py:5: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  q3_x = numpy.percentile(x, 75, interpolation='midpoint')


# 18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
    Price (in dollars): [10, 15, 12, 8, 14]
    
    Sales: [100, 80, 90, 110, 95]
    
    Perform a simple linear regression to predict


In [34]:
X=pd.DataFrame([10, 15, 12, 8, 14])
y=pd.DataFrame([100, 80, 90, 110, 95])

In [35]:
X,y

(    0
 0  10
 1  15
 2  12
 3   8
 4  14,
      0
 0  100
 1   80
 2   90
 3  110
 4   95)

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.20,random_state=42)

In [39]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4, 1), (1, 1), (4, 1), (1, 1))

In [41]:
regressor=LinearRegression()

In [42]:
regressor.fit(X_train,y_train)

LinearRegression()

In [43]:
y_pred=regressor.predict(y_test)

In [44]:
y_pred

array([[-91.]])

In [45]:
y_test

0
1  80


# 19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    
    Calculate the standard error of the mean satisfaction score.



In [47]:
data=[7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
data

[7, 8, 9, 6, 8, 7, 9, 7, 8, 7]

In [48]:
from scipy.stats import sem

In [49]:
sem(data) # calculate standard error of mean

0.30550504633038933

# 20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    
    Sales (in thousands): [25, 30, 28, 20, 26]
    
    Perform a multiple regression analysis to predict sales based on advertising expenditure.



In [50]:
X=pd.DataFrame([10, 15, 12, 8, 14])
y=pd.DataFrame([25, 30, 28, 20, 26])
X,y

(    0
 0  10
 1  15
 2  12
 3   8
 4  14,
     0
 0  25
 1  30
 2  28
 3  20
 4  26)

In [51]:
## Split  the data model
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=10)

In [52]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((3, 1), (3, 1), (2, 1), (2, 1))

In [53]:
# Scalling the dataset
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [54]:
scaler

StandardScaler()

In [55]:
X_train_scaled,X_test_scaled

(array([[-1.38873015],
        [ 0.46291005],
        [ 0.9258201 ]]),
 array([[-0.46291005],
        [-2.31455025]]))

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
regression=LinearRegression()

In [58]:
regression

LinearRegression()

In [59]:
regression.fit(X_train_scaled,y_train)

LinearRegression()

In [60]:
## slopes of 8 features
regression.coef_

array([[1.69733685]])

In [61]:
## Intercept
regression.intercept_

array([27.])

In [63]:

y_pred_test=regression.predict(X_test_scaled)
y_pred_test

array([[26.21428571],
       [23.07142857]])

In [64]:
## PErformance metrics cost function
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,y_pred_test))
print(mean_absolute_error(y_test,y_pred_test))
print(np.sqrt(mean_squared_error(y_test,y_pred_test)))

6.311224489795921
2.428571428571429
2.5122150564384254


In [65]:

## R square and Adjusted R square
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred_test)
print(score)
## Adjusted R square
#display adjusted R-squared
1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.6055484693877549


/tmp/ipykernel_104/656209345.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)


-inf

In [66]:
import pickle
pickle.dump(scaler,open('scaler.pkl','wb'))
pickle.dump(regression,open('regressor.pkl','wb'))

In [67]:
model_regressor=pickle.load(open('regressor.pkl','rb'))
model_regressor.predict(X_test_scaled)

array([[26.21428571],
       [23.07142857]])

In [68]:
standard_scaler=pickle.load(open('scaler.pkl','rb'))

In [69]:
model_regressor.predict(standard_scaler.transform(X_test))

array([[26.21428571],
       [23.07142857]])